//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetiCup.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calendar()
        {
            this.Championships = new HashSet<Championships>();
        }
    
        public System.DateTime date_id { get; set; }
        public int year_quarter_id { get; set; }
        public int quarter_id { get; set; }
        public int year_month_id { get; set; }
        public int month_id { get; set; }
        public int year_week_id { get; set; }
        public int week_id { get; set; }
        public int day_of_week_id { get; set; }
        public System.DateTime date { get; set; }
        public int year { get; set; }
        public string quarters { get; set; }
        public string quarter { get; set; }
        public string months { get; set; }
        public string month { get; set; }
        public string weeks { get; set; }
        public string week { get; set; }
        public string day_of_week { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Championships> Championships { get; set; }
    }
}
