//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetiCup.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Championships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Championships()
        {
            this.Participants = new HashSet<Participants>();
            this.Timeline = new HashSet<Timeline>();
            this.Dostizheniya = new HashSet<Dostizheniya>();
            this.Organizer = new HashSet<Organizer>();
        }
    
        public int championship_id { get; set; }
        public string championship_name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_id { get; set; }
        public Nullable<int> year_quarter_id { get; set; }
        public Nullable<int> quarter_id { get; set; }
        public Nullable<int> year_month_id { get; set; }
        public Nullable<int> month_id { get; set; }
        public Nullable<int> year_week_id { get; set; }
        public Nullable<int> week_id { get; set; }
        public Nullable<int> day_of_week_id { get; set; }
        public string location { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> Participants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timeline> Timeline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostizheniya> Dostizheniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organizer> Organizer { get; set; }
    }
}
