//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetiCup.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbGoldbergEntities : DbContext
    {
        public dbGoldbergEntities()
            : base("name=dbGoldbergEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<Championships> Championships { get; set; }
        public virtual DbSet<Dostizheniya> Dostizheniya { get; set; }
        public virtual DbSet<Organizer> Organizer { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Timeline> Timeline { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
