//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetiCup.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeline
    {
        public int event_id { get; set; }
        public byte[] event_picture { get; set; }
        public int championship_id { get; set; }
        public string event_description { get; set; }
    
        public virtual Championships Championships { get; set; }
    }
}
